services:
  database:
    container_name: fridge-db
    build: 
      context: .
      dockerfile: Dockerfile
      target: database
    ports:
      - "5432:5432"
    volumes:
      - "fridge-db-volume:/var/lib/postgres/data"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fridge-db
      TZ: "Asia/Tokyo"
volumes:
  fridge-db-volume:
